//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WolfoSkinsMod.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WolfoSkinsMod.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ExeAxe4 {
            get {
                object obj = ResourceManager.GetObject("ExeAxe4", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] exeem {
            get {
                object obj = ResourceManager.GetObject("exeem", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ExegunEmTex {
            get {
                object obj = ResourceManager.GetObject("ExegunEmTex", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ExegunTex {
            get {
                object obj = ResourceManager.GetObject("ExegunTex", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ExeKitEm {
            get {
                object obj = ResourceManager.GetObject("ExeKitEm", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ExeKitTex {
            get {
                object obj = ResourceManager.GetObject("ExeKitTex", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] exeRamp {
            get {
                object obj = ResourceManager.GetObject("exeRamp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ExeTex {
            get {
                object obj = ResourceManager.GetObject("ExeTex", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] HanD_Diffuse {
            get {
                object obj = ResourceManager.GetObject("HanD_Diffuse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] HanD_Emission {
            get {
                object obj = ResourceManager.GetObject("HanD_Emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] HanDWeapon_Diffuse {
            get {
                object obj = ResourceManager.GetObject("HanDWeapon_Diffuse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] PinktexCaptainJacketDiffuseW {
            get {
                object obj = ResourceManager.GetObject("PinktexCaptainJacketDiffuseW", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] PinktexCaptainPaletteW {
            get {
                object obj = ResourceManager.GetObject("PinktexCaptainPaletteW", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] PinktexCaptainPaletteW2 {
            get {
                object obj = ResourceManager.GetObject("PinktexCaptainPaletteW2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] PinktexCaptainPaletteW3 {
            get {
                object obj = ResourceManager.GetObject("PinktexCaptainPaletteW3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] RailGunnerCamperMetalBackpack {
            get {
                object obj = ResourceManager.GetObject("RailGunnerCamperMetalBackpack", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] RailGunnerCamperMetalBody {
            get {
                object obj = ResourceManager.GetObject("RailGunnerCamperMetalBody", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] RailGunnerCamperMetalGun {
            get {
                object obj = ResourceManager.GetObject("RailGunnerCamperMetalGun", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] RoRRHANDTex {
            get {
                object obj = ResourceManager.GetObject("RoRRHANDTex", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] RoRRHANDTexEmission {
            get {
                object obj = ResourceManager.GetObject("RoRRHANDTexEmission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] skinChefIcon {
            get {
                object obj = ResourceManager.GetObject("skinChefIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] skinChefIconRed {
            get {
                object obj = ResourceManager.GetObject("skinChefIconRed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] skinEnforcerIcon {
            get {
                object obj = ResourceManager.GetObject("skinEnforcerIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] skinExecutionerIcon {
            get {
                object obj = ResourceManager.GetObject("skinExecutionerIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] skinIconCaptainRED {
            get {
                object obj = ResourceManager.GetObject("skinIconCaptainRED", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] skinIconCommando {
            get {
                object obj = ResourceManager.GetObject("skinIconCommando", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] skinIconCommandoSOTV {
            get {
                object obj = ResourceManager.GetObject("skinIconCommandoSOTV", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] skinIconCroco {
            get {
                object obj = ResourceManager.GetObject("skinIconCroco", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] skinIconCrocoLEMURIAN {
            get {
                object obj = ResourceManager.GetObject("skinIconCrocoLEMURIAN", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] skinIconEngi {
            get {
                object obj = ResourceManager.GetObject("skinIconEngi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] skinIconEngiBLUE {
            get {
                object obj = ResourceManager.GetObject("skinIconEngiBLUE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] skinIconHuntress {
            get {
                object obj = ResourceManager.GetObject("skinIconHuntress", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] skinIconHuntressYELLOW {
            get {
                object obj = ResourceManager.GetObject("skinIconHuntressYELLOW", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] skinIconLoader {
            get {
                object obj = ResourceManager.GetObject("skinIconLoader", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] skinIconLoaderALT {
            get {
                object obj = ResourceManager.GetObject("skinIconLoaderALT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] skinIconMage {
            get {
                object obj = ResourceManager.GetObject("skinIconMage", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] skinIconMageOrange {
            get {
                object obj = ResourceManager.GetObject("skinIconMageOrange", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] skinIconMerc {
            get {
                object obj = ResourceManager.GetObject("skinIconMerc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] skinIconMercRed {
            get {
                object obj = ResourceManager.GetObject("skinIconMercRed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] skinIconRailgunner {
            get {
                object obj = ResourceManager.GetObject("skinIconRailgunner", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] skinIconRailgunnerCAMPER {
            get {
                object obj = ResourceManager.GetObject("skinIconRailgunnerCAMPER", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] skinIconToolbot {
            get {
                object obj = ResourceManager.GetObject("skinIconToolbot", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] skinIconToolbot2 {
            get {
                object obj = ResourceManager.GetObject("skinIconToolbot2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] skinIconVoidSurvivor {
            get {
                object obj = ResourceManager.GetObject("skinIconVoidSurvivor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] skinIconVoidSurvivorIMP {
            get {
                object obj = ResourceManager.GetObject("skinIconVoidSurvivorIMP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texBanditRedCoatDiffuse {
            get {
                object obj = ResourceManager.GetObject("texBanditRedCoatDiffuse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texBanditRedCoatDiffusePURPLE {
            get {
                object obj = ResourceManager.GetObject("texBanditRedCoatDiffusePURPLE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texBanditRedDiffuse {
            get {
                object obj = ResourceManager.GetObject("texBanditRedDiffuse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texBanditRedDiffusePURPLE {
            get {
                object obj = ResourceManager.GetObject("texBanditRedDiffusePURPLE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texBanditRedEmission {
            get {
                object obj = ResourceManager.GetObject("texBanditRedEmission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texBanditRedEmissionPURPLE {
            get {
                object obj = ResourceManager.GetObject("texBanditRedEmissionPURPLE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texBanditRedSkinIcon {
            get {
                object obj = ResourceManager.GetObject("texBanditRedSkinIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texBanditRedSkinIconPURPLE {
            get {
                object obj = ResourceManager.GetObject("texBanditRedSkinIconPURPLE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texBanditShotgunDiffuse {
            get {
                object obj = ResourceManager.GetObject("texBanditShotgunDiffuse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texBanditShotgunDiffusePURPLE {
            get {
                object obj = ResourceManager.GetObject("texBanditShotgunDiffusePURPLE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texBugWingDiffuse {
            get {
                object obj = ResourceManager.GetObject("texBugWingDiffuse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texCaptainJacketDiffuseRED {
            get {
                object obj = ResourceManager.GetObject("texCaptainJacketDiffuseRED", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texCaptainPaletteRED2 {
            get {
                object obj = ResourceManager.GetObject("texCaptainPaletteRED2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texCaptainPinkSkinIcon {
            get {
                object obj = ResourceManager.GetObject("texCaptainPinkSkinIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texChefDefault {
            get {
                object obj = ResourceManager.GetObject("texChefDefault", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texChefRed {
            get {
                object obj = ResourceManager.GetObject("texChefRed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texClassicGunHMG {
            get {
                object obj = ResourceManager.GetObject("texClassicGunHMG", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texClassicGunSuper {
            get {
                object obj = ResourceManager.GetObject("texClassicGunSuper", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texCommandoPaletteDiffuse {
            get {
                object obj = ResourceManager.GetObject("texCommandoPaletteDiffuse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texCrocoDiffuse {
            get {
                object obj = ResourceManager.GetObject("texCrocoDiffuse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texCrocoDiffuseLEMURIAN {
            get {
                object obj = ResourceManager.GetObject("texCrocoDiffuseLEMURIAN", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texCrocoEmission {
            get {
                object obj = ResourceManager.GetObject("texCrocoEmission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texCrocoEmissionLEMURIAN {
            get {
                object obj = ResourceManager.GetObject("texCrocoEmissionLEMURIAN", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texCrocoPoisonMask {
            get {
                object obj = ResourceManager.GetObject("texCrocoPoisonMask", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texCrocoSpinesDiffuse {
            get {
                object obj = ResourceManager.GetObject("texCrocoSpinesDiffuse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texDroneBody {
            get {
                object obj = ResourceManager.GetObject("texDroneBody", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texDroneBodyEmission {
            get {
                object obj = ResourceManager.GetObject("texDroneBodyEmission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texEnforcer {
            get {
                object obj = ResourceManager.GetObject("texEnforcer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texEnforcer_Emission {
            get {
                object obj = ResourceManager.GetObject("texEnforcer_Emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texEnforcerGun {
            get {
                object obj = ResourceManager.GetObject("texEnforcerGun", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texEnforcerGun_Emission {
            get {
                object obj = ResourceManager.GetObject("texEnforcerGun_Emission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texEnforcerShield {
            get {
                object obj = ResourceManager.GetObject("texEnforcerShield", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texEngiDiffuseAlt2 {
            get {
                object obj = ResourceManager.GetObject("texEngiDiffuseAlt2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texEngiDiffuseAlt2BLUE {
            get {
                object obj = ResourceManager.GetObject("texEngiDiffuseAlt2BLUE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texEngiEmissionAlt2 {
            get {
                object obj = ResourceManager.GetObject("texEngiEmissionAlt2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texEngiEmissionAlt2BLUE {
            get {
                object obj = ResourceManager.GetObject("texEngiEmissionAlt2BLUE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texEngiTurretDiffuseAlt2 {
            get {
                object obj = ResourceManager.GetObject("texEngiTurretDiffuseAlt2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texEngiTurretDiffuseAlt2BLUE {
            get {
                object obj = ResourceManager.GetObject("texEngiTurretDiffuseAlt2BLUE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texExeAxeRamp {
            get {
                object obj = ResourceManager.GetObject("texExeAxeRamp", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texHANDSkinIconDefault {
            get {
                object obj = ResourceManager.GetObject("texHANDSkinIconDefault", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texHANDSkinIconRorr {
            get {
                object obj = ResourceManager.GetObject("texHANDSkinIconRorr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texHuntressDiffuse {
            get {
                object obj = ResourceManager.GetObject("texHuntressDiffuse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texHuntressDiffuseBow {
            get {
                object obj = ResourceManager.GetObject("texHuntressDiffuseBow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texHuntressDiffuseBowYELLOW {
            get {
                object obj = ResourceManager.GetObject("texHuntressDiffuseBowYELLOW", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texHuntressDiffuseYELLOW {
            get {
                object obj = ResourceManager.GetObject("texHuntressDiffuseYELLOW", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texHuntressEmission {
            get {
                object obj = ResourceManager.GetObject("texHuntressEmission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texHuntressEmissionYELLOW {
            get {
                object obj = ResourceManager.GetObject("texHuntressEmissionYELLOW", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texHuntressScarfDiffuseAltYELLOW {
            get {
                object obj = ResourceManager.GetObject("texHuntressScarfDiffuseAltYELLOW", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texLoaderPilotDiffuse {
            get {
                object obj = ResourceManager.GetObject("texLoaderPilotDiffuse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texLoaderPilotDiffuseALT {
            get {
                object obj = ResourceManager.GetObject("texLoaderPilotDiffuseALT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texMageDiffuseAlt {
            get {
                object obj = ResourceManager.GetObject("texMageDiffuseAlt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texMageDiffuseORANGE {
            get {
                object obj = ResourceManager.GetObject("texMageDiffuseORANGE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texMercDiffuse {
            get {
                object obj = ResourceManager.GetObject("texMercDiffuse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texMercDiffuseRed {
            get {
                object obj = ResourceManager.GetObject("texMercDiffuseRed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texMercEmission {
            get {
                object obj = ResourceManager.GetObject("texMercEmission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texMercEmissionRED {
            get {
                object obj = ResourceManager.GetObject("texMercEmissionRED", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texMercSwordDiffuse {
            get {
                object obj = ResourceManager.GetObject("texMercSwordDiffuse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texMercSwordDiffuseRed {
            get {
                object obj = ResourceManager.GetObject("texMercSwordDiffuseRed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRabbitEarsDiffuse {
            get {
                object obj = ResourceManager.GetObject("texRabbitEarsDiffuse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRailgunEmission {
            get {
                object obj = ResourceManager.GetObject("texRailgunEmission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRailgunEmissionCAMPER {
            get {
                object obj = ResourceManager.GetObject("texRailgunEmissionCAMPER", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRailGunnerDiffuse {
            get {
                object obj = ResourceManager.GetObject("texRailGunnerDiffuse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRailGunnerDiffuseCAMPER {
            get {
                object obj = ResourceManager.GetObject("texRailGunnerDiffuseCAMPER", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRampCrocoDiseaseDark {
            get {
                object obj = ResourceManager.GetObject("texRampCrocoDiseaseDark", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRampEngiAlt2 {
            get {
                object obj = ResourceManager.GetObject("texRampEngiAlt2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRampEngiAlt2BLUE {
            get {
                object obj = ResourceManager.GetObject("texRampEngiAlt2BLUE", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRampEngiAlt2BLUEForWeapons {
            get {
                object obj = ResourceManager.GetObject("texRampEngiAlt2BLUEForWeapons", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRampFallbootsRed {
            get {
                object obj = ResourceManager.GetObject("texRampFallbootsRed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRampHuntress {
            get {
                object obj = ResourceManager.GetObject("texRampHuntress", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRampHuntressRed {
            get {
                object obj = ResourceManager.GetObject("texRampHuntressRed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRampHuntressSoft {
            get {
                object obj = ResourceManager.GetObject("texRampHuntressSoft", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRampHuntressSoft2 {
            get {
                object obj = ResourceManager.GetObject("texRampHuntressSoft2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRampHuntressSoft2YELLOW {
            get {
                object obj = ResourceManager.GetObject("texRampHuntressSoft2YELLOW", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRampHuntressSoftYELLOW {
            get {
                object obj = ResourceManager.GetObject("texRampHuntressSoftYELLOW", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRampHuntressYELLOW {
            get {
                object obj = ResourceManager.GetObject("texRampHuntressYELLOW", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRampMageFire {
            get {
                object obj = ResourceManager.GetObject("texRampMageFire", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRampNullifierOffset {
            get {
                object obj = ResourceManager.GetObject("texRampNullifierOffset", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texRampNullifierOffsetIMP {
            get {
                object obj = ResourceManager.GetObject("texRampNullifierOffsetIMP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texSexforcerShieldGlass {
            get {
                object obj = ResourceManager.GetObject("texSexforcerShieldGlass", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texShieldBugDiffuse {
            get {
                object obj = ResourceManager.GetObject("texShieldBugDiffuse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texToolbotNew {
            get {
                object obj = ResourceManager.GetObject("texToolbotNew", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texToolbotNew2 {
            get {
                object obj = ResourceManager.GetObject("texToolbotNew2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texTreebotBlueFlowerDiffuse {
            get {
                object obj = ResourceManager.GetObject("texTreebotBlueFlowerDiffuse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texTreebotBlueFlowerDiffuseINV {
            get {
                object obj = ResourceManager.GetObject("texTreebotBlueFlowerDiffuseINV", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texTreebotBlueLeafDiffuse {
            get {
                object obj = ResourceManager.GetObject("texTreebotBlueLeafDiffuse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texTreebotBlueLeafDiffuseINV {
            get {
                object obj = ResourceManager.GetObject("texTreebotBlueLeafDiffuseINV", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texTreebotBlueSkinIcon {
            get {
                object obj = ResourceManager.GetObject("texTreebotBlueSkinIcon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texTreebotBlueSkinIconINV {
            get {
                object obj = ResourceManager.GetObject("texTreebotBlueSkinIconINV", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texTreebotBlueTreeBarkDiffuse {
            get {
                object obj = ResourceManager.GetObject("texTreebotBlueTreeBarkDiffuse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texTreebotBlueTreeBarkDiffuseINV {
            get {
                object obj = ResourceManager.GetObject("texTreebotBlueTreeBarkDiffuseINV", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texTrimSheetConstructionLoaderAlt1 {
            get {
                object obj = ResourceManager.GetObject("texTrimSheetConstructionLoaderAlt1", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texTrimSheetConstructionLoaderAltALT {
            get {
                object obj = ResourceManager.GetObject("texTrimSheetConstructionLoaderAltALT", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texTrimSheetMilitaryLightMetal {
            get {
                object obj = ResourceManager.GetObject("texTrimSheetMilitaryLightMetal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texTrimSheetRailGunnerMetalBody {
            get {
                object obj = ResourceManager.GetObject("texTrimSheetRailGunnerMetalBody", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texVoidSurvivorFleshDiffuse {
            get {
                object obj = ResourceManager.GetObject("texVoidSurvivorFleshDiffuse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texVoidSurvivorFleshDiffuseIMP {
            get {
                object obj = ResourceManager.GetObject("texVoidSurvivorFleshDiffuseIMP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texVoidSurvivorFleshEmission {
            get {
                object obj = ResourceManager.GetObject("texVoidSurvivorFleshEmission", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] texVoidSurvivorFleshEmissionIMP {
            get {
                object obj = ResourceManager.GetObject("texVoidSurvivorFleshEmissionIMP", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
